### PR TITLE
Add TikTok

### PR DESCRIPTION
**Pull request by Zhiyu-Lei**

### CODE REVIEW

**Comment by Mazzaleen** [comment]
Is this Git repo any tech roles? im not finding much new grad swe ones, hoping it would be relevant to that

**Comment by NAlexH2** [comment]
> Is this Git repo any tech roles? im not finding much new grad swe ones, hoping it would be relevant to that

It's historically been that way. Though, it's awfully quiet this year for some reason.

**Comment by hessam94** [comment]
> 

Do you have any idea if they hire recent grad, may 2023, for 2023 early positions?
And what are the reasons for not publishing the roles here anymore? 

Thanks

**Comment by Mazzaleen** [comment]
https://github.com/ReaVNaiL/New-Grad-2024 is better

**Comment by Mazzaleen** [comment]
> > 
> 
> Do you have any idea if they hire recent grad, may 2023, for 2023 early positions? And what are the reasons for not publishing the roles here anymore?
> 
> Thanks

https://github.com/ReaVNaiL/New-Grad-2024 is better

**Pull request closed without merging**
