### PR TITLE
Add Apple

### PR DESCRIPTION
**Pull request by aaronwangj**
Adding Apple hardware position :)

### CODE REVIEW

**Review by kuschwyze — COMMENTED** [review]
Nice, it seems to be internship though

**Comment by aaronwangj** [comment]
My bad, I added the wrong one. Here's the hardware engineer new grad one.

**Comment by ushrestha57** [comment]
This was made in november of last year. Do you think this is still ongoing? It does say "Will be graduating with a minimum of a Bachelor's degree by September 2023"

**Comment by danerwilliams** [comment]
I don't think this position is for 2024 grads, closing

**Pull request closed without merging**
